version: '3.4'

services:
  restarter:
    image: docker
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
    command: [ "/bin/sh", "-c", "while true; do sleep 7200; docker restart twitter_parser_main_1; done" ]
    restart: unless-stopped
  main:
    build: ./
    command: python3 main.py
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 1Gb
    logging:
      driver: "json-file"
      options:
        max-size: "100m"