version: '3.4'

services:
  main:
    build: ./
    command: python3 main.py
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 1Gb
    logging:
      driver: "json-file"
      options:
        max-size: "100m"